version: "3.9"

services:

  backend:
    restart: always
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - backend/.env
    depends_on:
      - db
    networks:
      - db-net
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8001"


  db:
    restart: always
    image: postgres
    container_name: exchange_postgres
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - db-net

  frontend:
    restart: always
    command: npm start
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - backend
    networks:
      - db-net

volumes:
  postgres_data:

networks:
  db-net:
    driver: bridge
